### ISSUE TITLE
UnhandledPromiseRejectionWarning on macOS

### ISSUE THREAD

**Issue by eregon** [actions/setup-ruby#18]
https://github.com/ruby/spec/pull/683/checks?check_run_id=202172164
```
Run actions/setup-ruby@v1
  with:
    ruby-version: 2.5.x
do ln -sf /Users/runner/hostedtoolcache/Ruby/2.5.5/x64/bin/ruby /usr/bin/ruby
##[add-path]/Users/runner/hostedtoolcache/Ruby/2.5.5/x64/bin
ln: /usr/bin/ruby: Operation not permitted
(node:825) UnhandledPromiseRejectionWarning: Error: The process 'sudo' failed with exit code 1
    at ExecState._setResult (/Users/runner/runners/2.157.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:547:25)
    at ExecState.CheckComplete (/Users/runner/runners/2.157.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:530:18)
    at ChildProcess.<anonymous> (/Users/runner/runners/2.157.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:430:27)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
(node:825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems the `ln -sf` fails on macOS. The build still works nevertheless.

Actually, what tool requires `/usr/bin/ruby` to be the same as `ruby` in `PATH`?
AFAIK other CIs and all 3 major Ruby managers do not touch `/usr/bin/ruby`.
I saw https://github.com/actions/setup-ruby/blob/623660d1366330cb8f0b2a6243e9659429eaeed5/src/installer.ts#L18-L20
but in my experience there is no such problem with RubyGems (as long as `gem` is on PATH too alongside `ruby`, but that should always be the case).

I think if such a workaround is needed, it should be done only in those needed cases, not by `setup-ruby`, what do you think?

**Comment by chrishough** [comment]
I am having this same problem, is there a work around?

**Comment by eregon** [comment]
PR to fix this in https://github.com/actions/setup-ruby/pull/29

**Comment by chrishough** [comment]
Thank you @eregon

**Comment by eregon** [comment]
This is still not in `@v1` (see #81).
`v1` is very old: https://github.com/actions/setup-ruby/tree/v1 = 50f3cc9f0b0ab0fc1ed658c07aee4b1d61970143
Probably `v1` should be updated to `v1.1.1`.

In any case, probably best to use https://github.com/ruby/setup-ruby which is more actively maintained.
cc @alexisbronchart
