### ISSUE TITLE
Using GitHub Actions with Ruby on Rails and Postgres

### ISSUE THREAD

**Issue by alanvardy** [actions/setup-ruby#25]
I have been working on getting Rails and Postgres to work with Actions without a lot of success.

My difficulty is around connecting to the database. It is declared healthy, but I am not able to find the right combination of environment variables to make the magic happen.
[Link to config files](https://github.com/alanvardy/alanvardy/tree/develop/.github/workflows)

Is there a Rails example I can work off of?

Thank you!

**Comment by alanvardy** [comment]
My next push after leaving this comment succeeded.

Would you like me to open a pull request with a working example?

**Comment by leesmith** [comment]
@alanvardy Thanks so much for the rails + postgres example! I've got a similar setup but was struggling to get something to work. Thanks again!

**Comment by damccorm** [comment]
> Would you like me to open a pull request with a working example?

Sure, that would be great!

**Comment by EdSancha** [comment]
@alanvardy Can I take a look into your implementation? I'm trying to accomplish the same thign and running into issues with bundler and PG.

Thanks!!

**Comment by alanvardy** [comment]
Oh! Dead link and I haven't gotten around to actually making that PR :disappointed: 

I have two actions currently, one for unit tests and one for system tests. You can see them here!

https://github.com/alanvardy/alanvardy/tree/develop/.github/workflows

I'll update that link up top too :slightly_smiling_face:

**Comment by EdSancha** [comment]
🥇 Thanks a lot! This is really helpful
