### ISSUE TITLE
Ruby 2.5.7 support

### ISSUE THREAD

**Issue by timolehto** [actions/setup-ruby#36]
Updating our ruby version, but now with actions our CI is unable to use the latest 2.5.x Ruby to run tests etc.

https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/

**Comment by shrmnk** [comment]
Same here. Are there timelines from the time of release to the availability of ruby versions?

![image](https://user-images.githubusercontent.com/859780/67659875-6ec10700-f998-11e9-8357-8ccfafbae00e.png)

**Comment by dansteele** [comment]
I need ruby 2.6.5, and unless we can get support for that then unfortunately it's a no-go from the offset. I think this is going to be a pretty ubiquitous requirement for any serious app.  🙏

**Comment by clupprich** [comment]
Hej! I built https://github.com/clupprich/ruby-build-action over the weekend, which makes use of [ruby-build](https://github.com/rbenv/ruby-build) to install _exactly_ the version of Ruby you need. 

While that sounds (and actually _is_) slow, you can use the [actions/cache](https://github.com/actions/cache) action to cache the Ruby installation in your workflows (which brings the time it takes to setup Ruby down to ~30 seconds).

Let me know if that works for you. Feeback/issue reports/contributions welcome!

**Comment by dansteele** [comment]
@clupprich That absolutely solved this for me, and I imagine it will do so for many others! Great job.
💯 💯 💯 💯 💯 💯

**Comment by leesmith** [comment]
Thanks @clupprich...that worked perfectly! Not sure how useful setup-ruby is when you can't specify the exact ruby version you need.

**Comment by MSP-Greg** [comment]
Not that everyone is testing on Windows, but I created [MSP-Greg/actions-ruby](https://github.com/MSP-Greg/actions-ruby), which installs current Ruby versions (along with ruby-head/master) and allows updating the gcc build tools/packages on Windows.

Ruby 2.3.3 is also available, but if used for extension gems, it compiles with the newer 'DevKit'...

**Comment by frankieroberto** [comment]
+1 for Ruby 2.5.7 support.

**Comment by fbjork** [comment]
+1

**Comment by frankieroberto** [comment]
I think this requires an update to the virtual environment, so I’ve requested it here: https://github.com/actions/virtual-environments/issues/95

**Comment by erikstrottmann** [comment]
What are the currently supported Ruby versions? Our actions started failing today with a similar message, `Version 2.5.5 not found`.

<img width="428" alt="Screen Shot 2019-12-17 at 3 10 33 PM" src="https://user-images.githubusercontent.com/2874864/71042085-a36f5600-20df-11ea-97eb-89f592e0137c.png">

The [support page](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015) linked by @konradpabjan in https://github.com/actions/setup-python/issues/15#issuecomment-551222017 still says that Ruby 2.5.5 is supported.

**Comment by konradpabjan** [comment]
Ruby 2.5.5 should work. Just tested it out: 
![image](https://user-images.githubusercontent.com/16109154/71113635-07575480-219c-11ea-843b-50693ef7909e.png)

https://github.com/konradpabjan/Testing3/commit/9561e0ac0a4e7dcd4ab209aa0aacd3e4df02203c/checks?check_suite_id=365213462#step:4:4

Looking at the tools cache where the Ruby gets downloaded from, I still see version 2.5.5. It gets added here and automatically documented: https://github.com/actions/virtual-environments/blob/9786a9946a6db1a8d0c89948550753f9e01007b3/images/linux/scripts/installers/1804/hosted-tool-cache.sh#L39

If there are issues with the documented versions then `actions/virtual-environments` is the best place to report it.

**Comment by erikstrottmann** [comment]
2.5.5 is working for us again today. Thanks for testing it.

**Comment by bryanmacfarlane** [comment]
Closing since 2.5.5 is working and there's already a tracking item in virtual-environments.

Note a related issue: https://github.com/actions/setup-ruby/issues/44

**Comment by frankieroberto** [comment]
2.5.7 is now available, and 2.5.5 has been removed.

**Comment by bryanmacfarlane** [comment]
See #49 - flushing out ideas

I have a prototype working locally where we download JIT from rvm if it's not already in the VM cache.   I will have an experimental ref soon.  The plan is to fall back ruby-build after that (which also has the benefits of self-hosted runners). @clupprich - I may pull inspiration from yours and/or you can have a look at my experimental branch.  The ADR proposes using factored out caching logic (lib) so the consumer doesn't have to do the caching (probably just a bool option).
