### ISSUE TITLE
Abandoned repo?

### ISSUE THREAD

**Issue by veganstraightedge** [actions/setup-ruby#42]
I really like this action. I love how simple it makes adding a Ruby to a workflow. I would really love to continue to use it instead of Dockerizing all of the things. However, it seems like this repo is abandoned and not actively maintained.

If it is abandoned, would it possible for GitHub to find some other folx to own it, please? Having first party, top level support for Ruby in Actions feels really important to me.

❤️

**Comment by ioquatix** [comment]
@dmarcey who is maintaining this gem? Is GitHub willing to sponsor me to maintain it?

**Comment by MSP-Greg** [comment]
@ioquatix

Not sure if the issue is this action, or the fact that MSFT/GitHub aren't interested in timely updates to the images.

So, along with this repo (or a new one owned by Ruby?), maybe somewhere Ruby packages can be created to allow their use on Actions?

**Comment by ioquatix** [comment]
This should be the official action repo, and we should be enhancing it. It would make sense for people close to Ruby to be maintaining it. Can you share your actions repo?

**Comment by MSP-Greg** [comment]
https://github.com/MSP-Greg/actions-ruby

**Comment by MSP-Greg** [comment]
I'm wondering whether a possible solution is to create an action that wraps RVM?

One reason to wrap it with an action is the 'ENV' isolation that exists with Actions steps...

**Comment by ioquatix** [comment]
I discussed this with @oceanicpanda and I hope it's okay to mention some of the ideas they had here.

One idea was to use Heroku buildpacks, or at least provide that as an option.

I'm not against using RVM, but I wonder if we should just compile from source or use something really simple like `ruby-build` or `ruby-install`. Ideally we want to support JRuby and TruffleRuby as easily as possible.

**Comment by bryanmacfarlane** [comment]
It is not abandoned :) .  It was hectic with GA and now holidays.  I'll get some focus on it.  Thanks for the bump.

**Comment by solnic** [comment]
> @ioquatix I'm not against using RVM, but I wonder if we should just compile from source or use something really simple like ruby-build or ruby-install. Ideally we want to support JRuby and TruffleRuby as easily as possible.

Can we please please please try to use `ruby-install` and switch to rvm only when there is really a serious need for it?

I'm more than happy to help with this repo btw. We've adopted GH Actions in all dry-rb repos and we're in the process of doing the same thing in rom-rb and having to special-case JRuby in our CI setups was somewhat problematic and made things more complex. We would also love to start running our spec suites against TruffleRuby but as long as it's not trivial to set it up, we won't do it.

ps. sorry for commenting on a closed issue, I was late to the party ;)

**Comment by eregon** [comment]
This discussion in general is continuing on https://github.com/actions/setup-ruby/issues/44

> I'm more than happy to help with this repo btw. We've adopted GH Actions in all dry-rb repos and we're in the process of doing the same thing in rom-rb and having to special-case JRuby in our CI setups was somewhat problematic and made things more complex. We would also love to start running our spec suites against TruffleRuby but as long as it's not trivial to set it up, we won't do it.

See https://github.com/actions/setup-ruby/pull/28 for TruffleRuby support (but not yet reviewed).

https://github.com/actions/setup-ruby/issues/44#issuecomment-570062076 is a prototype of an action that makes it easy to use MRI, JRuby and TruffleRuby on Linux and macOS.
