### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by eregon** [actions/setup-ruby#45]
Ruby 2.7.0 has been released:
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

Would it be possible to add it to this action?

It would be very useful for ruby/spec: https://github.com/ruby/spec/pull/744

**Comment by pkuczynski** [comment]
I am waiting for this too!

**Comment by eregon** [comment]
FWIW, https://github.com/eregon/use-ruby-action/ supports Ruby 2.7.0 on Ubuntu and macOS.

**Comment by bryanmacfarlane** [comment]
This is currently a concern of the VM repo and the dupe issue is here https://github.com/actions/virtual-environments/issues/209
