### ISSUE TITLE
Supported Ruby versions

### ISSUE THREAD

**Issue by pkuczynski** [actions/setup-ruby#46]
How one can find out which versions of Ruby are available?

**Comment by masa-iwasaki** [comment]
@pkuczynski You can fined them at [actions/virtual-environments](https://github.com/actions/virtual-environments).

For example, [this README](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) contains the list of softwares installed on Ubuntu 18.04 virtual machine including Ruby.

**Comment by pkuczynski** [comment]
@masa-iwasaki none of the pasted links contain information which Ruby is available...

**Comment by MSP-Greg** [comment]
@pkuczynski

Please check again, all the README's in https://github.com/actions/virtual-environments/tree/master/images list Rubies.

Regardless, as to hosted Rubies, all are:

Ruby 2.4.6
Ruby 2.5.5
Ruby 2.6.3

Work is being done to allow installation of current Rubies for 2.3 thru 2.7, along with JRuby & TruffleRuby.  The work is community supported, no word from GitHub yet...

**Comment by pkuczynski** [comment]
I see. It would be good to point people to this link, otherwise it's hard to determine what's available.

This list of Rubies is quite outdated. I ended up using https://github.com/eregon/use-ruby-action/

**Comment by MSP-Greg** [comment]
> This list of Rubies is quite outdated. I ended up using https://github.com/eregon/use-ruby-action/

That's what I was referring to.  Speaking of rvm, and being a Windows type, does rvm do anything with cert files?  Windows installs ship with one, but not sure how they're handled on Ubuntu & macOS...

**Comment by pkuczynski** [comment]
Not sure what you mean with cert files?

**Comment by bryanmacfarlane** [comment]
Please log issues for new versions in the VM repo.  e.g. https://github.com/actions/virtual-environments/issues/209

**Comment by eregon** [comment]
I think it would be useful to link to a list of supported Ruby versions from the README though.
That data is really hard to find for people which don't know a lot of details about GitHub Actions.

**Comment by tisba** [comment]
Taken from https://github.com/actions/virtual-environments/issues/281 it would be great to at least make **very** clear that `actions/setup-ruby` is **not able to install versions of Ruby**, just setup predefined ones.

IMO there does not need to be a list in this repository, a reference to the currently available versions would be sufficient.

**Comment by eregon** [comment]
I made a PR to try to clarify this in the README: https://github.com/actions/setup-ruby/pull/52

**Comment by bryanmacfarlane** [comment]
I updated the readme with the simpler statement which clarifies what the workflow author should do.
