### ISSUE TITLE
Ruby versions do not seem available on macos-latest

### ISSUE THREAD

**Issue by eregon** [actions/setup-ruby#9]
https://github.com/ruby/spec/runs/191169968
```
Run actions/setup-ruby@v1
  with:
    version: 2.4.x
##[error]Version 2.4.x not found
##[error]Node run failed with exit code 1
```
The same happens when using `2.5.x` and `2.6.x`.

OTOH it works fine on `ubuntu-latest` and `windows-latest`.

Is this the right place to report this issue?

**Comment by damccorm** [comment]
> Is this the right place to report this issue?

Yep, this is probably the best place. @kaylangan it looks like this is not just an issue for Ruby - the tool cache seems to be empty on macOS. Any idea why? It looks like RUNNER_TOOL_CACHE is getting set to `/Users/runner/hostedtoolcache`, is that right?

**Comment by kaylangan** [comment]
This is a known issue. The tool cache should be in place by EOW and we'll deploy after that. ETA for full deployment is early/mid next week.

**Comment by eregon** [comment]
@kaylangan This seems fixed now, thank you for the quick fix!
https://github.com/ruby/spec/pull/683/checks?check_run_id=202172164
