### ISSUE TITLE
Error: Unable to process command '##[add-path]/opt/hostedtoolcache/Ruby/2.6.6/x64/bin' successfully.

### ISSUE THREAD

**Issue by truongnmt** [actions/setup-ruby#90]
I'm currently using `actions/setup-ruby@v1.1.1` version.
This morning my workflow failed with the following error:

![image](https://user-images.githubusercontent.com/11817656/99491648-78584b00-29af-11eb-85d2-2f77e687fffd.png)

> Run actions/setup-ruby@v1.1.1
  with:
    ruby-version: 2.6.x
Error: Unable to process command '##[add-path]/opt/hostedtoolcache/Ruby/2.6.6/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

**Comment by eregon** [comment]
Using `@v1` or `@v1.1.2` should fix that.

**Comment by truongnmt** [comment]
Thanks for your answer :D
