### ISSUE TITLE
Ruby 3

### ISSUE THREAD

**Issue by kvz** [actions/setup-ruby#92]
Ruby [3.0 was released](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) and I'd like to kick its tires in CI to see if the performance gain will be as good as for some of the highlighted scenarios, but it seems setup-ruby does not support `3.0.0` or similar yet. Could this be added? Thank you for this action! ❤️

**Comment by eregon** [comment]
[This other action](https://github.com/ruby/setup-ruby) (the official Ruby org action, and the one recommended in [starter-workflows](https://github.com/actions/starter-workflows/blob/main/ci/ruby.yml)) now has Ruby 3.0.0.

**Comment by kvz** [comment]
Works, thank you, happy holidays 🎄
